### ISSUE TITLE
maximum minimum range

### ISSUE THREAD

**Issue by vasilakisfil** [RSSchermer/ember-rl-week-picker#1]
Thank you for your component. I would like to be able to inject the maximum/minimum week/year, thus defining a range from which a user can select.

**Comment by RSSchermer** [comment]
That's an interesting idea :thumbsup:. I'll look into it over the weekend.

**Comment by RSSchermer** [comment]
I just published 0.1.0. You should now be able to set the `minWeek` and `maxWeek` properties with a week string formatted as `{year}-W{weekNumber}`, e.g. `2015-W6` for 2015 week 6. You'll need to update the css to get proper dimming of values (table rows for weeks outside the valid range get an `out-of-range` class added). You might want to rerun the generators again after updating. Let me know if this is what you needed and if you encounter any problems.

**Comment by vasilakisfil** [comment]
Ok perfect, I will update in a few hours and let you know :)

**Comment by vasilakisfil** [comment]
Hi! It worked perfect! Many thanks :+1: :+1: :+1:

**Comment by RSSchermer** [comment]
Good to hear!
